#!/usr/bin/env python
# -*- coding: utf-8 -*-


# application parameters
class app_params:

    sat_list            = {'7.0E': 'http://it.kingofsat.net/tv-7.0E.php',
                           '9.0E': 'http://it.kingofsat.net/tv-9.0E.php',
                           '10.0E': 'http://it.kingofsat.net/tv-10.0E.php',
                           '13.0E': 'http://it.kingofsat.net/tv-13.0E.php',
                           '14.5E': 'http://it.kingofsat.net/tv-14.5E.php',
                           '16.0E': 'http://it.kingofsat.net/tv-16.0E.php',
                           '17.0E': 'http://it.kingofsat.net/tv-17.0E.php',
                           '19.2E': 'http://it.kingofsat.net/tv-19.2E.php',
                           '20.0E': 'http://it.kingofsat.net/tv-20.0E.php',
                           '21.6E': 'http://it.kingofsat.net/tv-21.6E.php',
                           '23.5E': 'http://it.kingofsat.net/tv-23.5E.php',
                           '25.5E': 'http://it.kingofsat.net/tv-25.5E.php',
                           '26.0E': 'http://it.kingofsat.net/tv-26.0E.php',
                           '28.2E': 'http://it.kingofsat.net/tv-28.2E.php',
                           '30.7E': 'http://it.kingofsat.net/tv-30.7E.php',
                           '31.4E': 'http://it.kingofsat.net/tv-31.4E.php',
                           '39.0E': 'http://it.kingofsat.net/tv-39.0E.php',
                           '42.0E': 'http://it.kingofsat.net/tv-42.0E.php',
                           '45.0E': 'http://it.kingofsat.net/tv-45.0E.php',}

    
    sat_id              = {'7.0E': '7.0',
                           '9.0E': '9.0',
                           '10.0E': '10.0',
                           '13.0E': '13.0',
                           '14.5E': '14.5',
                           '16.0E': '16.0',
                           '17.0E': '17.0',
                           '19.2E': '19.2',
                           '20.0E': '20.0',
                           '21.6E': '21.6',
                           '23.5E': '23.5',
                           '25.5E': '25.5',
                           '26.0E': '26.0',
                           '28.2E': '28.2',
                           '30.7E': '30.7',
                           '31.4E': '31.4',
                           '39.0E': '39.0',
                           '42.0E': '42.0',
                           '45.0E': '45.0',}
    
    
                           
    caid_bouquets       = {'SkyItalia'          : '919,93B,9CD', 
                           'TivùSat'            : '183D',
                           'RAI'                : '100,183D',
                           'AlJazeeraSport'     : '500',                       
                           'Bis'                : '500',
                           'SSR/SRG'            : '500',
                           'Nova'               : '604',
                           'Cyfra+'             : '100,B00',
                           'CyfrowyPolsat'      : '1803,1801',
                           'N'                  : 'B01',
                           'Austriasat'         : 'D05',
                           'CanalDigitaal'      : '100',
                           'Canal+'             : '1810',
                           'CanalSat'           : '500,100,1811',
                           'CS Link'            : 'D0F',
                           'DigitAlb'           : 'B00',
                           'HD+'                : '1830',
                           'NC+'                : '100',
                           'Orange'             : '500',
                           'OrangePolska'       : '500',
                           'ORFDigital'         : 'D05,D95,648',
                           'PinkInternational'  : '91F',
                           'SkyDeutschland'     : '1833,1702,9C4',
                           'SkyDigital'         : '963',
                           'SkyLink'            : 'D96,624',
                           'TeleSat'            : '100,500',
                           'Telewizjanakartę'   : 'B00',
                           'TotalTV'            : '91F,D06',
                           'TringDigital'       : 'BAA',
                           'TVVlaanderen'       : '100,500',
                           'UPCDirect'          : 'D02,1815,D00',
                           'Bulsatcom'          : '4AEE',
                           'POLARI'             : '4AEE',
                           'Dolce TV'           : '4AEE',
                           'Bulgaria Sat'       : '4AEE',
                           'POLARIS'            : '4AEE'}
